config/routes.rb
Runbookapp::Application.routes.draw do
  devise_for :users

  resources :applications do
    resources :pages
  end

  root to: "applications#index"
end

app/models/application.rb
class Application < ActiveRecord::Base

  belongs_to :user
  has_many :pages
end

app/models/page.rb
class Page < ActiveRecord::Base
  belongs_to :application
  mount_uploader :image, ImageUploader

  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :applications, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :pdf

  def index
    @applications = current_user.applications
  end

  def new
    @application = current_user.applications.build
  end

  def create
    @application = current_user.applications.build(application_params)
    @application.save
    respond_with @application
  end

  def show
    @application = current_user.applications.find(params[:id])

    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "#{@application.name.parameterize}.pdf",
          layout: 'application'
      end
    end
  end

  def edit
    @application = current_user.applications.find(params[:id])
  end

  def update
    @application = current_user.applications.find(params[:id])
    @application.update_attributes(application_params)
    @application.save
    respond_with @application
  end


  private

  def application_params
    params.require(:application).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :find_application
  respond_to :html, :json

  def new
    @page = @application.pages.build
  end

  def create
    @page = @application.pages.build(page_params)
    if @page.save
      redirect_to @application
    else
      render :new
    end
  end

  def show
    @page = @application.pages.find(params[:id])
  end

  def update
    @page = @application.pages.find(params[:id])
    @page.update_attributes(page_params)
    respond_with @page
  end

  def destroy
    @page = @application.pages.find(params[:id])
    @page.destroy
    render :status => :ok
  end

  private
  def find_application
    @application = current_user.applications.find(params[:application_id])
  end

  def page_params
    params.require(:page).permit(:image,
                                 :remote_image_url,
                                 :title,
                                 :description,
                                 :sidebar,
                                 :footer,
                                 :folder,
                                 :order)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/applications/_application.html.erb
<% application.pages.group_by{|p| p.folder.downcase}.each do |folder, pages| %>
  <h3 class="folder"><%= folder %></h3>
  <ul class="media-list">
    <%pages.sort_by{|p| p.order.to_i}.each do |page|%>
      <li class="media">
      <%= link_to [application, page], class: "pull-left" do %>
        <%= image_tag page.image.url(:thumb), class: "media-thumb"%>
      <% end %>
      <div class="media-body">
        <%= link_to "Delete", [application, page], 
          class: "btn btn-danger btn-small pull-right",
          method: :delete,
          remote: true, 
          "data-confirm"=>"Are you sure?"
        %>
        <h4 class="media-heading"><%= page.title%></h4>
        <%= truncate page.description, length: 100%>
      </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/applications/_form.html.erb
<%= simple_form_for @application do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn btn-large btn-primary'%>
<% end %>

app/views/applications/_table_of_contents.pdf.erb
<% application.pages.group_by{|p| p.folder.downcase}.sort.each do |folder, pages| %>
  <h3 class="page_title"><%= folder%></h3>
  <ul class="unstyled">
    <%pages.sort_by{|p| p.order.to_i}.each do |page|%>
      <li><%= page.title%></li>
    <% end %>
  </ul>
<% end %>

app/views/applications/edit.html.erb
<div class="well">
  <h1>Update Application</h1>
</div>

<%= render partial: 'form' %>

app/views/applications/index.html.erb
<div class="well">
  <div class="pull-right">
    <%=link_to "Create Application", [:new, :application], class: "btn btn-primary" %>
  </div>
  <h1>Your Applications</h1>
</div>


<% if @applications.any? -%>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>th</th>
    </tr>
    <% @applications.each do |app| %>
      <tr>
        <td><%=link_to app.name, app %></td>
        <td>
          <%=link_to 'PDF', application_path(app, format: :pdf), class: 'btn' %>
          <%=link_to 'edit', [:edit, app], class: 'btn' %>
          <%=link_to 'destroy', app, class: 'btn', "data-confirm"=>'Are you positive?', method: :destroy %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <div>No Applications</div>
<% end %>

app/views/applications/new.html.erb
<div class="well">
  <h1>Create Application</h1>
</div>

<%= render partial: 'form' %>

app/views/applications/show.html.erb
<div class="well">
  <div class="pull-right">
    <%=link_to "Edit Application", [:edit, @application], class: "btn" %>
  </div>
  <h1>Application: <%= @application.name %></h1>
</div>


<%= link_to "Create Page", [:new, @application, :page], class: "btn btn-primary pull-right" %>
<h2>Pages <%= @application.pages.count %></h2>

<div id="application">
  <%= render @application %>
</div>

app/views/applications/show.pdf.erb
<div class="section_title">
  <h1><%= @application.name %> Runbook</h1></div>
</div>
<div class="row">
  <div class="span10 offset2 section_title">
    <p>Created on: <%= Time.now.strftime("%b %d, %Y") %></p>
    <p>Applications: iSurgery and iVendor</p>
  </div>
</div>
<div class="page_break"></div>


<div class="row">
  <div class="span10 offset2">
  <%= render partial: 'applications/table_of_contents', 
    locals: {application: @application}%>
  </div>
</div>
<div class="page_break"></div>

<% @application.pages.group_by{|p| p.folder.downcase}.sort.each do |folder, pages| %>

  <div class="section_title"><h1><%= folder %></h1></div>
  <div class="page_break"></div>


  <%pages.sort_by{|p| p.order.to_i}.each do |page|%>
    <div class="row">
      <div class="span12">
        <%= content_tag(:h1, page.title, class: 'report-title')%>
      </div>
    </div>
    <div class="well">
      <p>
        <%= page.description %>
      </p>
    </div>
    <div class="page">
      <div class="main">
        <%= image_tag page.image.url(:page), id: "page-image"%>
        <br/>
        <div class="footer">
          <%= page.footer %>
        </div>
      </div>
      <aside> 
        <%= page.sidebar %>
      </aside>
    </div>
    <div class="page_break"></div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Runbookapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= params[:controller] %>" data-action="<%= params[:action] %>">

  <div class="container">
    <%= yield %>
  </div>

  <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
</body>
</html>

app/views/layouts/application.pdf.erb
<!DOCTYPE html>
<html>
<head>
  <title>Runbookapp</title>
  <%= wicked_pdf_stylesheet_link_tag "application" %>
  <%= wicked_pdf_javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body data-controller="<%= params[:controller] %>" data-action="<%= params[:action] %>">

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/_form.html.erb
<%= simple_form_for [@application, @page] do |f| %>
  <%= f.input :title, input_html: {class: :span8}%>
  <%= f.input :folder %>
  <%= f.input :order %>
  <%= f.input :description, as: :text%>
  <%= f.input :sidebar, as: :text %>
  <%= f.input :footer, as: :text%>
  <%= f.input :image if @page.errors[:image].any? %>
  <%= f.input :remote_image_url, as: :hidden%>
  <div id="fileDropPane">
    Drop files here
  </div>
  <div class="row">
    <div class="span2"><strong>Result:</strong></div>
    <div class="span10">
      <pre id="localDropResult"></pre>
    </div>
  </div>
  <%= f.submit class: "btn btn-primary btn-large" %>

<% end %>

app/views/pages/destroy.js.erb
<% if @page.errors.any? %>
  alert('<%= j @page.errors.full_messages.join(',') %>');
<% else %>
  $("#application").html("<%= j render @page.application %>");
<% end %>

app/views/pages/new.html.erb
<div class="well">
  <div class="pull-right">
    Adding Page to: <%= @application.name %>
  </div>
  <h1>New Page</h1>
  <%= render partial: 'form' %>
</div>

app/views/pages/show.html.erb
<div class="row">
  <div class="span12">
    <h1><%= best_in_place @page, :title, path: [@page.application, @page]%></h1>
    <ul class="breadcrumb">
      <li><%= link_to "Home", root_path%><span class="divider">/</span></li>
      <li><%= link_to "Application", @page.application%><span class="divider">/</span></li>
      <li class="active">Page</li>
    </ul>
    <div class="well">
      <p>
      <%= best_in_place @page, :description, 
        path: [@page.application, @page],
        type: :textarea%>
      </p>
    </div>
  </div>
</div>

<div class="page">
  <div class="main">
    <%= image_tag @page.image.url(:page), id: "page-image"%>
    <br/>
    <%= best_in_place @page, :remote_image_url, 
      path: [@page.application, @page],
      activator: "#page-image", nil: ' '%>
    <div class="footer">
      <%= best_in_place @page, :footer,
        path: [@page.application, @page],
        type: :textarea%>
    </div>
  </div>
  <aside> 
    <h6>Placement</h6>
    <ul>
      <li>Folder: <%= best_in_place @page, :folder, path: [@page.application, @page]%></li>
      <li>Order: <%= best_in_place @page, :order, path: [@page.application, @page]%></li>
    </ul>
    <%= best_in_place @page, :sidebar,
      path: [@page.application, @page],
      type: :textarea%>
  </aside>
</div>